## Load libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


## Load the dataset

In [ ]:
url = "https://raw.githubusercontent.com/LakshyaSatpal/bitcoin-prediction/master/used_data.csv"
data = pd.read_csv(url)

In [ ]:
data.head()

date_id          datetime_id    market  rpt_key        last    diff_24h  \
0  2017-05-31  2017-06-01 00:00:00  bitstamp  btc_eur     1996.72     2029.99   
1  2017-05-31  2017-06-01 00:00:00  bitflyer  btc_jpy   267098.00   269649.00   
2  2017-05-31  2017-06-01 00:00:00    korbit  btc_krw  3003500.00  3140000.00   
3  2017-05-31  2017-06-01 00:00:00  bitstamp  btc_usd     2237.40     2239.37   
4  2017-05-31  2017-06-01 00:00:00    okcoin  btc_usd     2318.82     2228.70   

   diff_per_24h         bid         ask         low        high        volume  \
0     -1.638924     2005.50     2005.56     1950.00     2063.73   2314.500750   
1     -0.946045   267124.00   267267.00   267124.00   267267.00  70922.880112   
2     -4.347134  3003500.00  3004000.00  3002000.00  3209500.00   6109.752872   
3     -0.087971     2233.09     2237.40     2154.28     2293.46  13681.282017   
4      4.043613     2319.40     2319.99     2129.78     2318.82   4241.641516   

            created_at           updated_at  
0  2017-05-31 14:59:36  2017-05-31 14:59:36  
1  2017-05-31 14:59:36  2017-05-31 14:59:36  
2  2017-05-31 14:59:36  2017-05-31 14:59:36  
3  2017-05-31 14:59:36  2017-05-31 14:59:36  
4  2017-05-31 14:59:36  2017-05-31 14:59:36

In [ ]:
data['rpt_key'].value_counts()

btc_usd       125438
fx_btc_jpy     62719
eth_krw        62719
etc_krw        62719
ltc_usd        62719
btc_jpy        62719
eth_btc        62719
btc_eur        62719
btc_krw        62719
Name: rpt_key, dtype: int64

## Subset USD

In [ ]:
df = data.loc[(data['rpt_key'] == 'btc_usd')]

In [ ]:
df.head()

date_id          datetime_id    market  rpt_key     last  diff_24h  \
3   2017-05-31  2017-06-01 00:00:00  bitstamp  btc_usd  2237.40   2239.37   
4   2017-05-31  2017-06-01 00:00:00    okcoin  btc_usd  2318.82   2228.70   
15  2017-06-01  2017-06-01 00:01:00  bitstamp  btc_usd  2248.39   2242.44   
16  2017-06-01  2017-06-01 00:01:00    okcoin  btc_usd  2320.42   2228.40   
23  2017-06-01  2017-06-01 00:02:00  bitstamp  btc_usd  2248.35   2238.58   

    diff_per_24h      bid      ask      low     high        volume  \
3      -0.087971  2233.09  2237.40  2154.28  2293.46  13681.282017   
4       4.043613  2319.40  2319.99  2129.78  2318.82   4241.641516   
15      0.265336  2247.77  2248.38  2154.28  2293.46  13701.698603   
16      4.129420  2320.99  2321.49  2129.78  2322.00   4260.261516   
23      0.436437  2248.35  2248.69  2154.28  2293.46  13742.110913   

             created_at           updated_at  
3   2017-05-31 14:59:36  2017-05-31 14:59:36  
4   2017-05-31 14:59:36  2017-05-31 14:59:36  
15  2017-05-31 15:00:36  2017-05-31 15:00:36  
16  2017-05-31 15:00:36  2017-05-31 15:00:36  
23  2017-05-31 15:01:36  2017-05-31 15:01:36

### Convert datetime_id to data type and filter dates greater than  2017-06-28 

In [ ]:
df = df.reset_index(drop=True)
df['datetime'] = pd.to_datetime(df['datetime_id'])
df = df.loc[df['datetime'] > pd.to_datetime('2017-06-28 00:00:00')]

In [ ]:
df = df[['datetime', 'last', 'diff_24h', 'diff_per_24h', 'bid', 'ask', 'low', 'high', 'volume']]

In [ ]:
df.head()

datetime     last  diff_24h  diff_per_24h      bid      ask  \
77762 2017-06-28 00:01:00  2344.00   2491.98     -5.938250  2335.01  2343.89   
77763 2017-06-28 00:01:00  2499.39   2682.25     -6.817411  2495.00  2499.33   
77764 2017-06-28 00:02:00  2337.18   2491.98     -6.211928  2337.18  2340.00   
77765 2017-06-28 00:02:00  2492.76   2682.25     -7.064591  2492.76  2495.00   
77766 2017-06-28 00:03:00  2335.02   2491.98     -6.298606  2335.01  2335.02   

          low     high        volume  
77762  2307.0  2473.19  20719.583592  
77763  2444.0  2780.62   2265.557866  
77764  2307.0  2473.19  20732.082581  
77765  2444.0  2780.62   2262.618866  
77766  2307.0  2473.19  20665.357191

### we require only the last value, so we subset that and convert it to numpy 


In [ ]:
df = df[['last']]

In [ ]:
dataset = df.values
dataset = dataset.astype('float32')

In [ ]:
dataset

array([[ 2344.        ],
       [ 2499.38989258],
       [ 2337.17993164],
       ..., 
       [ 2394.0300293 ],
       [ 2320.4699707 ],
       [ 2394.0300293 ]], dtype=float32)

Neural networks are sensitive to input data, especiallly when we are using activation functions like sigmoid or tanh activation functions are used. ISo we rescale our data to the range of 0-to-1, using MinMaxScaler

In [ ]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

In [ ]:
dataset

array([[ 0.1997695 ],
       [ 0.49828053],
       [ 0.18666792],
       ..., 
       [ 0.29587936],
       [ 0.15456724],
       [ 0.29587936]], dtype=float32)

In [ ]:
train_size = int(len(dataset) * 0.67)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]
print(len(train), len(test))

(31942, 15734)


Now let us define the function called create_dataset, which take two inputs, 

1. Dataset - numpy array that we want to convert into a dataset
2. look_back - number of previous time steps to use as input variables to predict the next time period


In [ ]:
# convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=1):
  dataX, dataY = [], []
  for i in range(len(dataset)-look_back-1):
    a = dataset[i:(i+look_back), 0]
    dataX.append(a)
    dataY.append(dataset[i + look_back, 0])
  return np.array(dataX), np.array(dataY)

In [ ]:
look_back = 10
trainX, trainY = create_dataset(train, look_back=look_back)
testX, testY = create_dataset(test, look_back=look_back)

In [ ]:
trainX

array([[ 0.1997695 ,  0.49828053,  0.18666792, ...,  0.49753141,
         0.19973087,  0.48600531],
       [ 0.49828053,  0.18666792,  0.4855442 , ...,  0.19973087,
         0.48600531,  0.18442059],
       [ 0.18666792,  0.4855442 ,  0.18251848, ...,  0.48600531,
         0.18442059,  0.48598576],
       ..., 
       [ 0.53376245,  0.69436169,  0.53105354, ...,  0.70821238,
         0.52058411,  0.70815468],
       [ 0.69436169,  0.53105354,  0.70823145, ...,  0.52058411,
         0.70815468,  0.52665424],
       [ 0.53105354,  0.70823145,  0.53320551, ...,  0.70815468,
         0.52665424,  0.70815468]], dtype=float32)

In [ ]:
trainY

array([ 0.18442059,  0.48598576,  0.19208527, ...,  0.52665424,
        0.70815468,  0.5206418 ], dtype=float32)

In [ ]:
# reshape input to be [samples, time steps, features]
trainX = np.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

## Build our Model

In [ ]:
model = Sequential()
model.add(LSTM(4, input_shape=(1, look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=100, batch_size=256, verbose=2)

In [ ]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

We have to invert the predictions before calculating error to so that reports will be in same units as our original data




In [ ]:
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

In [ ]:

trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:, 0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:, 0]))
print('Test Score: %.2f RMSE' % (testScore))


Train Score: 4.77 RMSE
Test Score: 5.57 RMSE


In [ ]:
# shift train predictions for plotting
trainPredictPlot = np.empty_like(dataset)
trainPredictPlot[:, :] = np.nan
trainPredictPlot[look_back:len(trainPredict) + look_back, :] = trainPredict

In [ ]:
 # shift test predictions for plotting
testPredictPlot = np.empty_like(dataset)
testPredictPlot[:, :] = np.nan
testPredictPlot[len(trainPredict) + (look_back * 2) + 1:len(dataset) - 1, :] = testPredict
 


In [1]:
plt.plot(df['last'], label='Actual')
plt.plot(pd.DataFrame(trainPredictPlot, columns=["close"], index=df.index).close, label='Training')
plt.plot(pd.DataFrame(testPredictPlot, columns=["close"], index=df.index).close, label='Testing')
plt.legend(loc='best')
plt.show()

NameError: ignored